[package]
name = "example-auto-reload"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum" }
listenfd = "1.0.2"
tokio = { version = "1", features = ["full"] }
